version: '3.9'

services:
  rabbitmq:
    container_name: node_rabbitmq
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: 'rabbitmq-diagnostics -q ping'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - node-rabbitmq-data:/var/lib/rabbitmq

volumes:
  node-rabbitmq-data:
